library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity top is
  port (
    DDR_addr        : inout STD_LOGIC_VECTOR (14 downto 0);
    DDR_ba          : inout STD_LOGIC_VECTOR (2 downto 0);
    DDR_cas_n       : inout STD_LOGIC;
    DDR_ck_n        : inout STD_LOGIC;
    DDR_ck_p        : inout STD_LOGIC;
    DDR_cke         : inout STD_LOGIC;
    DDR_cs_n        : inout STD_LOGIC;
    DDR_dm          : inout STD_LOGIC_VECTOR (3 downto 0);
    DDR_dq          : inout STD_LOGIC_VECTOR (31 downto 0);
    DDR_dqs_n       : inout STD_LOGIC_VECTOR (3 downto 0);
    DDR_dqs_p       : inout STD_LOGIC_VECTOR (3 downto 0);
    DDR_odt         : inout STD_LOGIC;
    DDR_ras_n       : inout STD_LOGIC;
    DDR_reset_n     : inout STD_LOGIC;
    DDR_we_n        : inout STD_LOGIC;
    FIXED_IO_ddr_vrn : inout STD_LOGIC;
    FIXED_IO_ddr_vrp : inout STD_LOGIC;
    FIXED_IO_mio    : inout STD_LOGIC_VECTOR (53 downto 0);
    FIXED_IO_ps_clk : inout STD_LOGIC;
    FIXED_IO_ps_porb: inout STD_LOGIC;
    FIXED_IO_ps_srstb: inout STD_LOGIC
  );
end entity top;

architecture RTL of top is

  ---------------------------------------------------------------------------
  -- Block design wrapper component (auto-generated by Vivado)
  ---------------------------------------------------------------------------
  component design_1_wrapper is
    port (
      BRAM_PORTA_0_addr : out STD_LOGIC_VECTOR (12 downto 0);
      BRAM_PORTA_0_clk  : out STD_LOGIC;
      BRAM_PORTA_0_din  : out STD_LOGIC_VECTOR (31 downto 0);
      BRAM_PORTA_0_dout : in  STD_LOGIC_VECTOR (31 downto 0);
      BRAM_PORTA_0_en   : out STD_LOGIC;
      BRAM_PORTA_0_rst  : out STD_LOGIC;
      BRAM_PORTA_0_we   : out STD_LOGIC_VECTOR (3 downto 0);
      DDR_addr          : inout STD_LOGIC_VECTOR (14 downto 0);
      DDR_ba            : inout STD_LOGIC_VECTOR (2 downto 0);
      DDR_cas_n         : inout STD_LOGIC;
      DDR_ck_n          : inout STD_LOGIC;
      DDR_ck_p          : inout STD_LOGIC;
      DDR_cke           : inout STD_LOGIC;
      DDR_cs_n          : inout STD_LOGIC;
      DDR_dm            : inout STD_LOGIC_VECTOR (3 downto 0);
      DDR_dq            : inout STD_LOGIC_VECTOR (31 downto 0);
      DDR_dqs_n         : inout STD_LOGIC_VECTOR (3 downto 0);
      DDR_dqs_p         : inout STD_LOGIC_VECTOR (3 downto 0);
      DDR_odt           : inout STD_LOGIC;
      DDR_ras_n         : inout STD_LOGIC;
      DDR_reset_n       : inout STD_LOGIC;
      DDR_we_n          : inout STD_LOGIC;
      FIXED_IO_ddr_vrn  : inout STD_LOGIC;
      FIXED_IO_ddr_vrp  : inout STD_LOGIC;
      FIXED_IO_mio      : inout STD_LOGIC_VECTOR (53 downto 0);
      FIXED_IO_ps_clk   : inout STD_LOGIC;
      FIXED_IO_ps_porb  : inout STD_LOGIC;
      FIXED_IO_ps_srstb : inout STD_LOGIC
    );
  end component design_1_wrapper;

  ---------------------------------------------------------------------------
  -- BRAM IP (from your blk_mem_gen_0 stub)
  ---------------------------------------------------------------------------
  component blk_mem_gen_0 is
    port (
      clka  : in  STD_LOGIC;
      ena   : in  STD_LOGIC;
      wea   : in  STD_LOGIC_VECTOR(0 downto 0);
      addra : in  STD_LOGIC_VECTOR(12 downto 0);
      dina  : in  STD_LOGIC_VECTOR(31 downto 0);
      douta : out STD_LOGIC_VECTOR(31 downto 0)
    );
  end component blk_mem_gen_0;

  ---------------------------------------------------------------------------
  -- Internal signals for BRAM connection between BD and blk_mem_gen_0
  ---------------------------------------------------------------------------
  signal bram_addr  : STD_LOGIC_VECTOR(12 downto 0);
  signal bram_clk   : STD_LOGIC;
  signal bram_din   : STD_LOGIC_VECTOR(31 downto 0);
  signal bram_dout  : STD_LOGIC_VECTOR(31 downto 0);
  signal bram_en    : STD_LOGIC;
  signal bram_rst   : STD_LOGIC;  -- currently unused, BD drives it
  signal bram_we    : STD_LOGIC_VECTOR(3 downto 0);

  -- Single-bit WE for blk_mem_gen_0
  signal bram_wea   : STD_LOGIC_VECTOR(0 downto 0);

begin

  ---------------------------------------------------------------------------
  -- Map 4-bit WE from BD to 1-bit WE of blk_mem_gen_0
  -- Use only LSB: any write will assert WE(0).
  ---------------------------------------------------------------------------
  bram_wea(0) <= bram_we(0);

  ---------------------------------------------------------------------------
  -- Block Design instantiation
  ---------------------------------------------------------------------------
  u_bd : design_1_wrapper
    port map (
      BRAM_PORTA_0_addr => bram_addr,
      BRAM_PORTA_0_clk  => bram_clk,
      BRAM_PORTA_0_din  => bram_din,
      BRAM_PORTA_0_dout => bram_dout,
      BRAM_PORTA_0_en   => bram_en,
      BRAM_PORTA_0_rst  => bram_rst,   -- not used further
      BRAM_PORTA_0_we   => bram_we,

      DDR_addr          => DDR_addr,
      DDR_ba            => DDR_ba,
      DDR_cas_n         => DDR_cas_n,
      DDR_ck_n          => DDR_ck_n,
      DDR_ck_p          => DDR_ck_p,
      DDR_cke           => DDR_cke,
      DDR_cs_n          => DDR_cs_n,
      DDR_dm            => DDR_dm,
      DDR_dq            => DDR_dq,
      DDR_dqs_n         => DDR_dqs_n,
      DDR_dqs_p         => DDR_dqs_p,
      DDR_odt           => DDR_odt,
      DDR_ras_n         => DDR_ras_n,
      DDR_reset_n       => DDR_reset_n,
      DDR_we_n          => DDR_we_n,
      FIXED_IO_ddr_vrn  => FIXED_IO_ddr_vrn,
      FIXED_IO_ddr_vrp  => FIXED_IO_ddr_vrp,
      FIXED_IO_mio      => FIXED_IO_mio,
      FIXED_IO_ps_clk   => FIXED_IO_ps_clk,
      FIXED_IO_ps_porb  => FIXED_IO_ps_porb,
      FIXED_IO_ps_srstb => FIXED_IO_ps_srstb
    );

  ---------------------------------------------------------------------------
  -- BRAM instance: shared LUT memory
  ---------------------------------------------------------------------------
  u_bram : blk_mem_gen_0
    port map (
      clka  => bram_clk,
      ena   => bram_en,
      wea   => bram_wea,
      addra => bram_addr,
      dina  => bram_din,
      douta => bram_dout
    );

end architecture RTL;
