# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0.xci
# IP: The module: 'design_1_axi_dma_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0.xci
# IP: The module: 'design_1_axi_dma_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/FACULTATE/facultate/anul3/sem1/SSC/proiect/utcn-bounding-box-detection-on-PYNQ-Z1/PL_retry/PL_retry.gen/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_dma_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
